substitutions:
  box_num: "51"
  box_name: "esptest"
  type: "esp32"
  board: "nodemcu-32s"
  comment: "38-pin narrow"
  update_interval: "1min"
  force_update: "true"

<<: !include .common.yaml

esphome:
  name: "${box_name}${box_num}"
  comment: "${type}: ${board} (${comment})"

web_server: !include include/web_server.yaml
button: !include include/button.yaml
captive_portal:

# logger:
# level: VERY_VERBOSE

# esp32_ble_beacon:
# type: iBeacon
# uuid: 'a7ea6c8a-bd4c-11ed-afa1-0242ac120002'

# light:
# - platform: rgb
# name: "Test LED ${box_num}"
# red: red_1
# green: green_1
# blue: blue_1

# output:
# - platform: ledc
# id: red_1
# pin: 32

# - platform: ledc
# id: green_1
# pin: 33

# - platform: ledc
# id: blue_1
# pin: 25

light:
  - platform: binary
    name: "Red ${box_num}"
    id: red_led
    output: red_o

  - platform: binary
    name: "Yellow ${box_num}"
    id: yellow_led
    output: yellow_o

  - platform: status_led
    name: "Green ${box_num}"
    id: green_led
    pin: 25

output:
  - id: red_o
    platform: gpio
    pin: 32

  - id: yellow_o
    platform: gpio
    pin: 33

  # - id: green_o
  # platform: gpio
  # pin: 25

i2c:
  scan: false

# esp32_ble_tracker:

binary_sensor:
  - platform: status
    name: "Status ${box_num}"

  - platform: gpio
    pin:
      number: 23
      mode: INPUT_PULLUP
    name: "Physical Button ${box_num}"
    entity_category: diagnostic
    icon: mdi:radiobox-marked
    filters:
      - invert:
    on_multi_click:
      - timing:
          - ON for at least 5s
        then:
          - logger.log: "5 Second Reset"
          - button.press: reboot_device
      # - timing:
      # - ON for at least 2s
      # - OFF for at least 0.1s
      # then:
      # - logger.log: "2 Second Light"
      # - light.toggle: main_led
      - timing:
          - ON for at most 4.9s
          - OFF for at least 0.1s
        then:
          - logger.log: "Single Click"
          - component.update: bmp280_sensor

  # - platform: ble_presence
  # ibeacon_uuid: 'f2d69d9d-5d4d-4d63-bb81-d65b712592cb'
  # name: "S10 BLE Presence"
  # device_class: presence

sensor:
  - platform: uptime
    name: "Uptime ${box_num}"
    update_interval: 5min

  - platform: wifi_signal
    name: "WiFi Signal ${box_num}"
    update_interval: "${update_interval}"
    force_update: true
    filters:
      - filter_out: 0
      - median:

  - platform: bmp280
    address: 0x76
    # update_interval: "${update_interval}"
    update_interval: "15s"
    id: bmp280_sensor
    temperature:
      name: "TestTemp${box_num}-280"
      force_update: ${force_update}
      filters:
        - lambda: |-
            float MIN = -39.0;
            float MAX = 79.0;
            if (MIN <= x && x <= MAX) return x;
            else return {};
      on_value_range:
        - below: 22.2
          then:
            - logger.log: "Green Light"
            - light.turn_on: green_led
            - light.turn_off: yellow_led
            - light.turn_off: red_led
        - above: 22.2
          below: 24.0
          then:
            - logger.log: "Yellow Light"
            - light.turn_on: yellow_led
            - light.turn_off: green_led
            - light.turn_off: red_led
        - above: 24.0
          then:
            - logger.log: "Red Light"
            - light.turn_on: red_led
            - light.turn_off: green_led
            - light.turn_off: yellow_led
    pressure:
      name: "TestPres${box_num}-280"
      force_update: ${force_update}

  # - platform: ble_rssi
  # ibeacon_uuid: 'f2d69d9d-5d4d-4d63-bb81-d65b712592cb'
  # name: "S10 BLE RSSI"
