# Temp/Humidity - Living Room

substitutions:
  # https://esphome.io/components/substitutions
  box_num: "03"
  box_name: "espbox"
  type: "esp32"
  board: "esp32dev"
  comment: "38-pin"

packages:
  # https://esphome.io/components/packages.html
  common: !include { file: include/common.yaml }
  status_led: !include
    file: include/status_led.yaml
    vars:
      pin: GPIO27

i2c:
  scan: false

sensor:
  - !include { file: include/sensor/dht22.yaml, vars: { pin: 19 } }
  - !include { file: include/sensor/absolute_humidity_dht22.yaml }
  - !include { file: include/sensor/bmp280.yaml, vars: { address: 0x76 } }
