# Temp/Humidity - Bedroom

substitutions:
  # https://esphome.io/components/substitutions
  friendly_name: "Bedroom Box"
  box_num: "01"
  box_name: "espbox"
  type: "esp32"
  board: "esp32dev"
  comment: "38-pin"

packages:
  # https://esphome.io/components/packages.html
  common: !include { file: include/common.yaml }
  status_led: !include { file: include/status_led.yaml, vars: { pin: 18 } }

binary_sensor:
  # https://esphome.io/#binary-sensor-components
  - !include { file: include/binary/btn_light_reset.yaml, vars: { pin: 27 } }

sensor:
  # https://esphome.io/#sensor-components
  - !include { file: include/sensor/dht22.yaml, vars: { pin: 33 } }
  - !include { file: include/sensor/absolute_humidity_dht22.yaml }
