# Temp/Humidity - Outside

substitutions:
  # https://esphome.io/components/substitutions
  box_num: "02"
  box_name: "espbox"
  type: "esp32"
  board: "esp32dev"
  comment: "38-pin"

packages:
  # https://esphome.io/components/packages.html
  common: !include { file: include/common.yaml }
  status_led: !include
    file: include/status_led.yaml
    vars:
      pin: GPIO27

binary_sensor:
  - !include { file: include/binary/btn_light_reset.yaml, vars: { pin: 18 } }

sensor:
  - !include { file: include/sensor/dht22.yaml, vars: { pin: 33 } }
  - !include { file: include/sensor/absolute_humidity_dht22.yaml }
