substitutions:
  box_num: "03"
  box_name: "espbox"
  type: "esp32"
  board: "esp32dev"
  comment: "38-pin"
  update_interval: "1min"
  force_update: "true"
  led_pin: "27"

<<: !include .common.yaml
<<: !include include/light-status_led.yaml

esphome:
  name: "${box_name}${box_num}"
  comment: "${type}: ${board} (${comment})"

web_server: !include include/web_server.yaml
button: !include include/button.yaml
captive_portal:

i2c:
  scan: false

binary_sensor:
  - platform: status
    name: "Status ${box_num}"

sensor:
  - platform: uptime
    name: "Uptime ${box_num}"
    update_interval: 5min

  - platform: internal_temperature
    name: "Core Temp ${box_num}"
    update_interval: 5min
    force_update: ${force_update}

  - platform: wifi_signal
    name: "WiFi Signal ${box_num}"
    update_interval: 1min
    force_update: true
    filters:
      - filter_out: 0
      - median:

  - platform: dht
    model: DHT22
    pin:
      number: 19
      mode: INPUT_PULLUP
    update_interval: "${update_interval}"
    temperature:
      name: "Temp${box_num}-22"
      id: "temp_${box_num}"
      force_update: ${force_update}
      filters:
        - lambda: |-
            float MIN = -39.0;
            float MAX = 79.0;
            if (MIN <= x && x <= MAX) return x;
            else return {};
    humidity:
      name: "Humi${box_num}-22"
      id: "humi_${box_num}"
      force_update: ${force_update}
      accuracy_decimals: 1
      filters:
        - filter_out: 0

  - platform: absolute_humidity
    name: "AbsHumi${box_num}"
    temperature: "temp_${box_num}"
    humidity: "humi_${box_num}"
    force_update: ${force_update}

  - platform: bmp280_i2c
    address: 0x76
    update_interval: "${update_interval}"
    temperature:
      name: "Temp${box_num}-280"
      force_update: ${force_update}
    pressure:
      name: "Pres${box_num}-280"
      force_update: ${force_update}
