substitutions:
  box_num: "03"
  box_name: "espbox"
  type: "esp32"
  board: "esp32dev"
  comment: "38-pin"
  update_interval: "1min"
  force_update: "true"

<<: !include .common.yaml
<<: !include { file: include/web_server.yaml, vars: { version: 3 } }

captive_portal:

light:
  - !include { file: include/light/status_led.yaml, vars: { pin: 27 } }

i2c:
  scan: false

text_sensor:
  - !include { file: include/text/version.yaml }
  - !include { file: include/text/wifi_info.yaml }

binary_sensor:
  - !include { file: include/binary/status.yaml }

sensor:
  - !include { file: include/sensor/internal_temperature.yaml }
  - !include { file: include/sensor/uptime.yaml }
  - !include { file: include/sensor/wifi_signal.yaml }
  - !include { file: include/sensor/dht22.yaml, vars: { pin: 19 } }
  - !include { file: include/sensor/absolute_humidity_dht22.yaml }
  - !include { file: include/sensor/bmp280.yaml, vars: { address: 0x76 } }
