# Temp/Humidity - Kitchen

substitutions:
  box_num: "04"
  box_name: "espbox"
  type: "esp32"
  board: "esp32dev"
  comment: "38-pin"

packages:
  common: !include { file: include/common.yaml }
  status_led: !include
    file: include/status_led.yaml
    vars:
      pin: GPIO23

binary_sensor:
  - !include { file: include/binary/btn_light_reset.yaml, vars: { pin: 19 } }

sensor:
  - !include { file: include/sensor/dht22.yaml, vars: { pin: 33 } }
  - !include { file: include/sensor/absolute_humidity_dht22.yaml }
