# BENCH - idk

substitutions:
  # https://esphome.io/components/substitutions
  friendly_name: "Test Box 53"
  box_num: "53"
  box_name: "esptest"
  type: "esp32"
  board: "nodemcu-32s"
  comment: "38-pin (narrow)"

packages:
  # https://esphome.io/components/packages.html
  common: !include { file: include/common.yaml }
  debug: !include { file: include/debug.yaml }
  status_led: !include
    file: include/status_led.yaml
    vars:
      pin: GPIO33

#${type}:
#  # https://esphome.io/#supported-microcontrollers
#  framework:
#    sdkconfig_options:
#      CONFIG_ESP32_DEFAULT_CPU_FREQ_240: "y"

esphome:
  # https://esphome.io/components/esphome
  on_boot:
    - priority: 400
      then:
        - logger.log: "Boot 400"
        - if:
            condition:
              - switch.is_off: photo_switch
            then:
              - logger.log: "Suspending: photoresistor"
              - component.suspend: photoresistor

web_server:
  # https://esphome.io/components/web_server
  version: 3
  sorting_groups:
    - id: sg_temps
      name: "Temperature"
      sorting_weight: -30

one_wire:
  # https://esphome.io/components/one_wire
  - platform: gpio
    pin: GPIO32

i2c:
  # https://esphome.io/components/i2c
  scan: false
  frequency: 400kHz

font:
  # https://esphome.io/components/font
  - file:
      type: gfonts
      family: "Red Hat Text"
    id: main_text
    size: 14
    #bpp: 4
    #glyphsets: [GF_Latin_Core]
    #extras:
    #  - file: "fonts/materialdesignicons-webfont.ttf"
    #    glyphs: &glyphs
    #      - "\U000F1B1E" # flash-triangle-outline
  - file:
      type: gfonts
      family: "Ubuntu Mono"
    id: ubuntu_text
    size: 18
    #bpp: 4
    #glyphsets: [GF_Latin_Core]
    #extras:
    #  - file: "fonts/materialdesignicons-webfont.ttf"
    #    glyphs: *glyphs

display:
  # https://esphome.io/#display-components
  - platform: ssd1306_i2c
    id: main_display
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      if (!global_api_server->is_connected() ) {
        it.printf(0, 0, id(main_text), "Connecting to HA...");
      } else {
        if (id(photo_switch).state) {
          it.printf(0, 0, id(ubuntu_text), "ADC:");
        } else {
          it.printf(0, 0, id(ubuntu_text), "OFF:");
        }
        it.printf(128, 0, id(ubuntu_text), TextAlign::RIGHT, "%.3f V", id(photoresistor).state);

        it.printf(0, 23, id(main_text), "Temp 1:");
        it.printf(128, 23, id(ubuntu_text), TextAlign::RIGHT, "%.1f C", id(temp1).state);

        it.printf(0, 46, id(main_text), "Temp 2:");
        it.printf(128, 46, id(ubuntu_text), TextAlign::RIGHT, "%.1f C", id(temp2).state);
      }
    #lambda: |-
    #  if (!global_api_server->is_connected() ) {
    #    it.printf(0, 0, id(main_text), "Connecting to HA...");
    #  } else {
    #    it.printf(0, 0, id(main_text), "IP:");
    #    it.printf(128, 0, id(main_text), TextAlign::RIGHT, "%s", id(wifi_info_ip).state.c_str());
    #  }
    #
    #  it.printf(0, 23, id(main_text), "Temp:");
    #  it.printf(128, 23, id(ubuntu_text), TextAlign::RIGHT, "%.1f C", id(temp1).state);
    #  //it.printf(128, 23, id(main_text), TextAlign::RIGHT, "%s", id(photo_switch).state ? "Active" : "PAUSED");
    #
    #  if (id(photo_switch).state) {
    #    it.printf(0, 46, id(ubuntu_text), "ADC:");
    #  } else {
    #    it.printf(0, 46, id(ubuntu_text), "OFF:");
    #  }
    #  it.printf(128, 46, id(ubuntu_text), TextAlign::RIGHT, "%.3f V", id(photoresistor).state);

button:
  # https://esphome.io/#button-components
  - !include
    file: include/button/update_component.yaml
    vars:
      name: Photoresistor
      component: photoresistor
      id: photo_btn

switch:
  # https://esphome.io/#switch-components
  - !include
    file: include/switch/toggle_component.yaml
    vars:
      name: "Photoresistor"
      component: photoresistor
      id: photo_switch
  - !include
    file: include/switch/toggle_component.yaml
    vars:
      name: "Dallas 1"
      component: temp1
      id: temp1_switch
      restore_mode: ALWAYS_ON
  - !include
    file: include/switch/toggle_component.yaml
    vars:
      name: "Dallas 2"
      component: temp2
      id: temp2_switch
      restore_mode: ALWAYS_ON

#binary_sensor:
#  # https://esphome.io/#binary-sensor-components
#  - platform: gpio
#    name: "Touch 1 - ${box_num}"
#    id: touch_1
#    icon: mdi:gesture-tap-box
#    pin:
#      number: 26
#      mode: INPUT_PULLUP
#    on_press:
#      then:
#        - switch.toggle: photo_switch

sensor:
  # https://esphome.io/#sensor-components
  - !include { file: include/sensor/photoresistor.yaml, vars: { pin: 36 } }
  #- !include { file: include/sensor/dallas_temp.yaml, vars: { id: temp1 } }
  - platform: dallas_temp
    name: "Temp${box_num}-1"
    id: temp1
    address: 0x80011453ddfcaa28
    #update_interval: 30s
    disabled_by_default: true
    force_update: ${force_update}
    filters:
      - filter_out: 85
      - clamp:
          min_value: -55
          max_value: 125
          ignore_out_of_range: true
    web_server:
      sorting_group_id: sg_temps
      sorting_weight: 10

  - platform: dallas_temp
    name: "Temp${box_num}-2"
    id: temp2
    address: 0xf8011453d4c3aa28
    #update_interval: 30s
    disabled_by_default: true
    force_update: ${force_update}
    filters:
      - filter_out: 85
      - clamp:
          min_value: -55
          max_value: 125
          ignore_out_of_range: true
    web_server:
      sorting_group_id: sg_temps
      sorting_weight: 11
