# PIR - BENCHED

substitutions:
  box_num: "48"
  box_name: "esptest"
  type: "esp32"
  board: "nodemcu-32s"
  comment: "38-pin (narrow)"
  update_interval: "1min"
  force_update: "true"

<<: !include { file: .common.yaml }

captive_portal:

debug:
  update_interval: 5min

${type}:
  board: "${board}"
  framework:
    type: esp-idf
    version: recommended

#esphome:
#  name: "${box_name}${box_num}"
#  comment: "${type}: ${board} (${comment})"
#  on_boot:
#    priority: -100
#    then:
#      - if:
#          condition:
#            - binary_sensor.is_on: presence
#            - switch.is_on: presence_light
#          then:
#            - logger.log: "light.turn_on: main_led"
#            - light.turn_on: main_led

api:
  encryption:
    key: !secret enc_key
  on_client_connected:
    - logger.log:
        format: "API Client: %s - IP: %s"
        args: ["client_info.c_str()", "client_address.c_str()"]
  on_client_disconnected:
    - logger.log: "API Client disconnected!"

web_server:
  port: 80
  ota: false
  version: 3
  sorting_groups:
    - id: sg_lights
      name: "Lights"
      sorting_weight: -30

light:
  - !include { file: include/light/status_led.yaml, vars: { pin: 26 } }

  - platform: monochromatic
    name: "Monochromatic Light ${box_num}"
    id: chromatic_led
    icon: mdi:lightbulb-outline
    output: mono_chromo
    effects: !include { file: include/light/effects/pulse.yaml }
    web_server:
      sorting_group_id: sg_lights
      sorting_weight: 10

#switch:
#  - platform: template
#    name: "Presence Light ${box_num}"
#    id: presence_light
#    icon: mdi:alarm-light-off-outline
#    optimistic: true
#    restore_mode: RESTORE_DEFAULT_OFF
#    turn_on_action:
#      - if:
#          condition:
#            - binary_sensor.is_on: presence
#          then:
#            - light.turn_on: mono_chromo
#    turn_off_action:
#      - light.turn_off: mono_chromo

#remote_receiver:
#  pin: GPIO23
#  dump: all
#  on_raw:
#    then:
#      - logger.log: "RX on_raw"
#      - light.toggle: rgb_led

output:
  - platform: ledc
    id: mono_chromo
    pin: GPIO25
    max_power: 80%

  #- platform: ledc
  #  id: rgb_r
  #  pin: GPIO27
  #  max_power: 75%
  #- platform: ledc
  #  id: rgb_g
  #  pin: GPIO14
  #  max_power: 80%
  #- platform: ledc
  #  id: rgb_b
  #  pin: GPIO12
  #  max_power: 80%

text_sensor:
  - !include { file: include/text/debug.yaml }
  - !include { file: include/text/version.yaml }
  - !include { file: include/text/wifi_info.yaml }

binary_sensor:
  - !include { file: include/binary/status.yaml }

  #- platform: gpio
  #  pin: GPIO19
  #  name: "Presence ${box_num}"
  #  id: presence
  #  #icon: mdi:motion-sensor
  #  device_class: motion
  #  #filters:
  #  #  - delayed_off: 60s
  #  on_press:
  #    then:
  #      - if:
  #          condition:
  #            - switch.is_on: presence_light
  #          then:
  #            - light.turn_on: main_led
  #  on_release:
  #    then:
  #      - light.turn_off: main_led

  - platform: gpio
    name: "Touch 1 - ${box_num}"
    id: touch_1
    icon: mdi:gesture-tap-box
    pin:
      number: 16
      mode: INPUT_PULLUP
    on_press:
      then:
        - light.toggle: chromatic_led

sensor:
  - !include { file: include/sensor/debug.yaml }
  - !include { file: include/sensor/internal_temperature.yaml }
  - !include { file: include/sensor/uptime.yaml }
  - !include { file: include/sensor/wifi_signal.yaml }
