# BENCHED

substitutions:
  box_num: "51"
  box_name: "esptest"
  type: "esp32"
  board: "nodemcu-32s"
  comment: "38-pin (narrow)"
  update_interval: "1min"
  force_update: "true"

<<: !include .common.yaml
<<: !include { file: include/web_server.yaml, vars: { version: 3 } }

captive_portal:

debug:
  update_interval: 5min

#logger:
#  level: DEBUG
#  baud_rate: 0

api:
  encryption:
    key: !secret enc_key

#interval:
#  - interval: 15s
#    then:
#      - logger.log: "15s Interval"
#      - logger.log:
#          format: "WiFi IP 1: %s"
#          args: ["id(wifi_ip).state.c_str()"]
#      - lambda: |-
#          ESP_LOGI("main", "WiFi IP 2: %s", WiFi.localIP().toString().c_str());

light:
  - !include { file: include/light/status_led.yaml, vars: { pin: 32 } }

button:
  - !include { file: include/button/restart.yaml }
  - !include { file: include/button/safe_mode.yaml }

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: false
  frequency: 400kHz

one_wire:
  - platform: gpio
    pin: GPIO33

font:
  - file: "fonts/arial.ttf"
    id: font1
    size: 14
  - file: "fonts/arial.ttf"
    id: font2
    size: 16

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    #reset_pin: D0
    #update_interval: 5s
    lambda: |-
      if (!id(ha_status).state) {
        it.printf(0, 0, id(font1), "Connecting...");
      } else {
        it.printf(0, 0, id(font1), "IP:");
        it.printf(128, 0, id(font1), TextAlign::RIGHT, "%s", id(wifi_ip).state.c_str());

        it.printf(0, 23, id(font2), "Fridge:");
        it.printf(128, 23, id(font2), TextAlign::RIGHT, "%.1f°F", id(temp1).state * 1.8 + 32);

        it.printf(0, 46, id(font2), "Freezer:");
        it.printf(128, 46, id(font2), TextAlign::RIGHT, "%.1f°F", id(temp2).state * 1.8 + 32);

      }

text_sensor:
  - !include { file: include/text/debug.yaml }
  - !include { file: include/text/version.yaml }
  - !include { file: include/text/wifi_info.yaml }

  - platform: homeassistant
    name: "WiFi IP Address"
    id: wifi_ip
    entity_id: sensor.wifi_ip_51

binary_sensor:
  - !include { file: include/binary/status.yaml }
  - !include { file: include/binary/ha_status.yaml }

  - platform: gpio
    pin:
      number: 19
      mode: INPUT_PULLUP
    name: "Physical Button ${box_num}"
    icon: mdi:radiobox-marked
    filters:
      - invert:
    on_click:
      - min_length: 1ms
        max_length: 1000ms
        then:
          - logger.log: ">1 Second Single Click"
          - light.toggle: main_led
      - min_length: 1001ms
        max_length: 4999ms
        then:
          - logger.log: "1-5 Second Long Press"
      - min_length: 5000ms
        max_length: 10000ms
        then:
          - logger.log: "5< Second Long Press"

sensor:
  - !include { file: include/sensor/debug.yaml }
  - !include { file: include/sensor/internal_temperature.yaml }
  - !include { file: include/sensor/uptime.yaml }
  - !include { file: include/sensor/wifi_signal.yaml }

  - platform: dallas_temp
    name: "Temp${box_num}-1"
    id: temp1
    address: 0x80011453ddfcaa28
    update_interval: 15s
    #force_update: ${force_update}

  - platform: dallas_temp
    name: "Temp${box_num}-2"
    id: temp2
    address: 0xf8011453d4c3aa28
    update_interval: 15s
    #force_update: ${force_update}
