# BENCH - idk

substitutions:
  # https://esphome.io/components/substitutions
  friendly_name: "Test Box 53"
  box_num: "53"
  box_name: "esptest"
  type: "esp32"
  board: "nodemcu-32s"
  comment: "38-pin (narrow)"

packages:
  # https://esphome.io/components/packages.html
  debug: !include { file: include/debug.yaml }
  common: !include { file: include/common.yaml }
  status_led: !include
    file: include/status_led.yaml
    vars:
      pin: GPIO33

${type}:
  # https://esphome.io/#supported-microcontrollers
  framework:
    sdkconfig_options:
      CONFIG_ESP32_DEFAULT_CPU_FREQ_240: "y"

i2c:
  # https://esphome.io/components/i2c
  sda: GPIO21 # green
  scl: GPIO22 # blue
  scan: false
  frequency: 400kHz

font:
  # https://esphome.io/components/font
  - file:
      type: gfonts
      family: "Red Hat Text"
    id: redhat14
    size: 14
    #bpp: 4
    #glyphsets: [GF_Latin_Core]
    #extras:
    #  - file: "fonts/materialdesignicons-webfont.ttf"
    #    glyphs: &glyphs
    #      - "\U000F1B1E" # flash-triangle-outline
  - file:
      type: gfonts
      family: "Ubuntu Mono"
    id: ubuntu14
    size: 14
    #bpp: 4
    #glyphsets: [GF_Latin_Core]
    #extras:
    #  - file: "fonts/materialdesignicons-webfont.ttf"
    #    glyphs: *glyphs

display:
  # https://esphome.io/#display-components
  - platform: ssd1306_i2c
    id: main_display
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      if (!global_api_server->is_connected() ) {
        it.printf(0, 0, id(redhat14), "Connecting to HA...");
      } else {
        it.printf(0, 0, id(redhat14), "IP:");
        it.printf(128, 0, id(redhat14), TextAlign::RIGHT, "%s", id(wifi_info_ip).state.c_str());
      }

      it.printf(0, 23, id(redhat14), "Status:");
      it.printf(128, 23, id(redhat14), TextAlign::RIGHT, "%s", id(photo_switch).state ? "Active" : "PAUSED");

      it.printf(0, 46, id(ubuntu14), "ADC:");
      it.printf(128, 46, id(ubuntu14), TextAlign::RIGHT, "%.3f V", id(photoresistor).state);

button:
  # https://esphome.io/#button-components
  - !include
    file: include/button/update_component.yaml
    vars:
      name: Photoresistor
      component: photoresistor
      id: photo_btn

switch:
  # https://esphome.io/#switch-components
  - !include
    file: include/switch/toggle_component.yaml
    vars:
      name: Photoresistor
      component: photoresistor
      id: photo_switch

binary_sensor:
  # https://esphome.io/#binary-sensor-components
  - platform: gpio
    name: "Touch 1 - ${box_num}"
    id: touch_1
    icon: mdi:gesture-tap-box
    pin:
      number: 26
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: photo_switch

sensor:
  # https://esphome.io/#sensor-components
  - platform: adc
    # https://esphome.io/components/sensor/adc
    name: "Photoresistor ${box_num}"
    id: photoresistor
    icon: mdi:lightning-bolt-circle
    pin: GPIO36
    attenuation: 12db
    update_interval: 1s
    disabled_by_default: true
