# ld2450 - Kitchen

substitutions:
  # https://esphome.io/components/substitutions
  box_num: "47"
  box_name: "esptest"
  type: "esp32"
  board: "nodemcu-32s"
  comment: "38-pin (narrow)"

packages:
  # https://esphome.io/components/packages.html
  debug: !include { file: include/debug.yaml }
  common: !include { file: include/common.yaml }
  status_led: !include
    file: include/status_led.yaml
    vars:
      pin: GPIO33
  ld2450: !include
    file: include/ld2450/ld2450.yaml
    vars:
      rx_pin: GPIO16
      tx_pin: GPIO17

logger:
  # https://esphome.io/components/logger
  logs:
    sensor: INFO
    component: ERROR

binary_sensor:
  - platform: ld2450
    has_target:
      name: "Presence ${box_num}"
      #id: presence
      on_press:
        then:
          - light.turn_on: main_led
      on_release:
        then:
          - light.turn_off: main_led
    has_moving_target:
      name: "Moving Target ${box_num}"
    has_still_target:
      name: "Still Target ${box_num}"
