# ld2450 - Kitchen

substitutions:
  # https://esphome.io/components/substitutions
  friendly_name: "Test Box 47"
  box_num: "47"
  box_name: "esptest"
  type: "esp32"
  board: "nodemcu-32s"
  comment: "38-pin (narrow)"

packages:
  # https://esphome.io/components/packages.html
  debug: !include { file: include/debug.yaml }
  common: !include { file: include/common.yaml }
  status_led: !include
    file: include/status_led.yaml
    vars:
      pin: GPIO33
  ld2450: !include
    file: include/ld2450/ld2450.yaml
    vars:
      rx_pin: GPIO16
      tx_pin: GPIO17

${type}:
  # https://esphome.io/#supported-microcontrollers
  framework:
    sdkconfig_options:
      CONFIG_ESP32_DEFAULT_CPU_FREQ_240: "y"

logger:
  # https://esphome.io/components/logger
  logs:
    sensor: INFO
    component: ERROR

binary_sensor:
  # https://esphome.io/#binary-sensor-components
  - platform: ld2450
    has_target:
      name: "Presence ${box_num}"
      id: presence
      on_press:
        then:
          - light.turn_on: main_led
      on_release:
        then:
          - light.turn_off: main_led
    #has_target:
    #  !include {
    #    file: include/ld2420/has_target_night_light.yaml,
    #    vars: { light: main_led, switch: bedroom_light },
    #  }
    has_moving_target:
      name: "Moving Target ${box_num}"
      disabled_by_default: true
    has_still_target:
      name: "Still Target ${box_num}"
      disabled_by_default: true

  #- id: !extend ld2450_binary_sensor
  #  # This custom package can not be extended because it does not allow an ID
  #  has_target:
  #    on_press:
  #      then:
  #        - light.turn_on: main_led
  #    on_release:
  #      then:
  #        - light.turn_off: main_led
