substitutions:
  box_num: "51"
  box_name: "esptest"
  type: "esp32"
  board: "nodemcu-32s"
  comment: "38-pin (narrow)"
  update_interval: "1min"
  force_update: "true"

<<: !include .common.yaml
<<: !include { file: include/web_server.yaml, vars: { version: 3 } }

captive_portal:

debug:
  update_interval: 5min

logger:
  baud_rate: 0
  #logs:
  #  component: ERROR

api:
  encryption:
    key: !secret enc_key
  actions:
    - action: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda "return song_str;"

light:
  - !include { file: include/light/status_led.yaml, vars: { pin: 32 } }

button:
  - !include { file: include/button/restart.yaml }
  - !include { file: include/button/safe_mode.yaml }

  - platform: ld2420
    apply_config:
      name: Apply Config
    factory_reset:
      name: Factory Reset
    restart_module:
      name: Restart Module
    revert_config:
      name: Undo Edits

#switch:
#  - platform: gpio
#    name: "Buzzer ${box_num}"
#    id: buzzer
#    pin: GPIO19
#    icon: "mdi:volume-high"

output:
  - platform: ledc
    pin: GPIO33
    id: rtttl_out

rtttl:
  output: rtttl_out
  on_finished_playback:
    - logger.log: "Playback Finished."

#one_wire:
#  - platform: gpio
#    pin: GPIO14

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: false
  frequency: 400kHz

uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200

font:
  - file: "fonts/arial.ttf"
    id: font1
    size: 14

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    #reset_pin: D0
    #update_interval: 5s
    lambda: |-
      if (id(custom_text_input).state.empty()) {
        it.printf(0, 0, id(font1), "Connecting...");
      } else {
        it.printf(0, 0, id(font1), "%s", id(custom_text_input).state.c_str());
      }
      if (id(presence).state) {
        it.print(0, 23, id(font1), "Somebody is Here");
      } else {
        it.print(0, 23, id(font1), "Nobody is Here");
      }
      it.printf(0, 46, id(font1), "Distance: %.1f", id(moving_distance).state);

ld2420:

select:
  - platform: ld2420
    operating_mode:
      name: Operating Mode

number:
  - platform: ld2420
    presence_timeout:
      name: Detection Presence Timeout
    min_gate_distance:
      name: Detection Gate Minimum
    max_gate_distance:
      name: Detection Gate Maximum

    gate_select:
      name: Select Gate to Set
    still_threshold:
      name: Set Still Threshold Value
    move_threshold:
      name: Set Move Threshold Value

    gate_move_sensitivity:
      name: Move Calibration Sensitivity Factor
    gate_still_sensitivity:
      name: Still Calibration Sensitivity Factor

    gate_0:
      move_threshold:
        name: Gate 0 Move Threshold
      still_threshold:
        name: Gate 0 Still Threshold
    gate_1:
      move_threshold:
        name: Gate 1 Move Threshold
      still_threshold:
        name: Gate 1 Still Threshold

text_sensor:
  - !include { file: include/text/debug.yaml }
  - !include { file: include/text/version.yaml }
  - !include { file: include/text/wifi_info.yaml }

  - platform: ld2420
    fw_version:
      name: "LD2420 Firmware ${box_num}"

  - platform: homeassistant
    name: "Custom Text Input"
    id: custom_text_input
    entity_id: input_text.custom_text

binary_sensor:
  - !include { file: include/binary/status.yaml }
  #- !include { file: include/binary/ha_status.yaml }

  - platform: gpio
    pin:
      number: 19
      mode: INPUT_PULLUP
    name: "Physical Button ${box_num}"
    icon: mdi:radiobox-marked
    filters:
      - invert:
    on_click:
      - logger.log: "BUTTON PRESSED"
      - rtttl.play: "HighMedium:d=4,o=6,b=120:c, e, c, e"
      #- rtttl.play: "one:d=4,o=4,b=240:6e6"
      #- rtttl.play: "long:d=2,o=5,b=100:e6"

  - platform: ld2420
    has_target:
      name: "Presence ${box_num}"
      id: presence
      on_press:
        then:
          - logger.log: "+++ PRESENCE DETECTED"
          - light.turn_on: main_led
          #- rtttl.play: "HighMedium:d=4,o=6,b=120:c, e, c, e"
      on_release:
        then:
          - logger.log: "--- NO PRESENCE"
          - light.turn_off: main_led

sensor:
  - !include { file: include/sensor/debug.yaml }
  - !include { file: include/sensor/internal_temperature.yaml }
  - !include { file: include/sensor/uptime.yaml }
  - !include { file: include/sensor/wifi_signal.yaml }

  #- platform: dallas_temp
  #  name: "Temp${box_num}-18"
  #  id: "temp_${box_num}"
  #  #address: 0xf8011453d4c3aa28
  #  update_interval: 5s

  - platform: ld2420
    moving_distance:
      name: "Moving Distance ${box_num}"
      id: moving_distance
