substitutions:
  box_num: "49"
  box_name: "esptest"
  type: "esp32"
  board: "nodemcu-32s"
  comment: "38-pin (narrow)"
  update_interval: "1min"
  force_update: "true"
  led_pin: "GPIO12"

<<: !include .common.yaml
<<: !include include/light-status_led.yaml

esphome:
  name: "${box_name}${box_num}"
  comment: "${type}: ${board} (${comment})"

web_server: !include include/web_server.yaml
#button: !include include/button.yaml
captive_portal:

button:
  - platform: restart
    name: "Reboot Device ${box_num}"
    id: reboot_device

  - platform: safe_mode
    name: "Reboot Safe Mode ${box_num}"

  - platform: ld2420
    apply_config:
      name: Apply Config
    factory_reset:
      name: Factory Reset
    restart_module:
      name: Restart Module
    revert_config:
      name: Undo Edits

#one_wire:
#  - platform: gpio
#    pin: GPIO14

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: false

uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200

logger:
  baud_rate: 0
  logs:
    component: ERROR

font:
  - file: "fonts/arial.ttf"
    id: font1
    size: 14

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    #reset_pin: D0
    #update_interval: 5s
    lambda: |-
      it.print(14, 0, id(font1), "Person Finder");
      // it.print(0, 23, id(font1), "RALPH BROKE IT");
      if (id(presence_${box_num}).state) {
        it.print(0, 23, id(font1), "Somebody is Here");
      } else {
        it.print(0, 23, id(font1), "Nobody is Here");
      }
      // it.print(0, 46, id(font1), "Confidence: 100%");
      it.printf(0, 46, id(font1), "Distance: %.1f", id(distance_${box_num}).state);

ld2420:

select:
  - platform: ld2420
    operating_mode:
      name: Operating Mode

text_sensor:
  - platform: ld2420
    fw_version:
      name: LD2420 Firmware

binary_sensor:
  - platform: status
    name: "Status ${box_num}"

  - platform: ld2420
    has_target:
      name: Presence
      id: "presence_${box_num}"
      on_press:
        then:
          - light.turn_on: main_led
      on_release:
        then:
          - light.turn_off: main_led

sensor:
  - platform: uptime
    name: "Uptime ${box_num}"
    update_interval: 5min

  - platform: internal_temperature
    name: "Core Temp ${box_num}"
    update_interval: 5min
    force_update: ${force_update}

  - platform: wifi_signal
    name: "WiFi Signal ${box_num}"
    update_interval: "${update_interval}"
    force_update: ${force_update}
    filters:
      - filter_out: 0
      - median:

  #- platform: dallas_temp
  #  name: "Temp${box_num}-18"
  #  id: "temp_${box_num}"
  #  #address: 0xf8011453d4c3aa28
  #  update_interval: 5s

  - platform: ld2420
    moving_distance:
      name: Moving Distance
      id: "distance_${box_num}"
