# ld2420 - Bathroom

substitutions:
  box_num: "50"
  box_name: "esptest"
  type: "esp8266"
  board: "nodemcuv2"
  comment: "full"

packages:
  #debug: !include { file: include/debug.yaml }
  common: !include { file: include/common.yaml }
  status_led: !include
    file: include/status_led.yaml
    vars:
      pin: D5
  ld2420: !include
    file: include/ld2420/ld2420.yaml
    vars:
      tx_pin: GPIO1
      rx_pin: GPIO3

${type}:
  framework:
    type: !remove

logger:
  baud_rate: 0

esphome:
  on_boot:
    - priority: -100
      then:
        - !include {
            file: include/esphome/night_light_boot.yaml,
            vars: { light: main_led, switch: night_light },
          }

switch:
  - !include {
      file: include/switch/night_light.yaml,
      vars: { light: main_led, binary: presence },
    }

  - platform: homeassistant
    name: "Bathroom Light"
    id: bathroom_light
    entity_id: light.bathroom_light

binary_sensor:
  - platform: ld2420
    has_target:
      name: "Presence ${box_num}"
      id: presence
      on_press:
        !include {
          file: include/ld2420/on_press_night_light.yaml,
          vars: { light: main_led, switch: bathroom_light },
        }
      on_release:
        !include {
          file: include/ld2420/on_release_night_light.yaml,
          vars: { light: main_led },
        }

  #- platform: gpio
  #  name: "Touch 1 - ${box_num}"
  #  id: touch_1
  #  icon: mdi:gesture-tap-box
  #  pin:
  #    number: 26
  #    mode: INPUT_PULLUP
  #  on_press:
  #    then:
  #      - switch.toggle: night_light

sensor:
  - id: !remove esp32_internal_temperature # not available on esp8266
