# BENCHED

substitutions:
  box_num: "52"
  box_name: "esptest"
  type: "esp32"
  board: "esp32dev"
  comment: "38-pin"
  update_interval: "1min"
  force_update: "true"

<<: !include { file: .common.yaml }

#external_components:
#  - source: github://jesserockz/esphome-components
#    components: [udp_audio]
#
#udp_audio:
#  ip_address: 192.168.1.20
#  port: 6056

captive_portal:

${type}:
  board: "${board}"
  framework:
    type: esp-idf
    version: recommended

esphome:
  name: "${box_name}${box_num}"
  comment: "${type}: ${board} (${comment})"
  on_boot:
    - priority: 200
      then:
        - logger.log: "Boot 200"
        - micro_wake_word.start:

api:
  encryption:
    key: !secret enc_key
  on_client_connected:
    - logger.log:
        format: "API Client: %s - IP: %s"
        args: ["client_info.c_str()", "client_address.c_str()"]
  on_client_disconnected:
    - logger.log: "API Client disconnected!"

web_server:
  port: 80
  ota: false
  version: 3
  sorting_groups:
    #- !include { file: include/web/groups/device.yaml }
    - id: sg_audio
      name: "Audio"
      sorting_weight: -20

debug:
  update_interval: 5min

light:
  - !include { file: include/light/status_led.yaml, vars: { pin: 26 } }

micro_wake_word:
  vad:
  models:
    - model: okay_nabu
    - model: hey_mycroft
    - model: hey_jarvis
  on_wake_word_detected:
    then:
      - logger.log: "+ + +  on_wake_word_detected  + + +"
      #- lambda: |-
      #    ESP_LOGI("micro_wake_word", "wake_word: %s", wake_word);
      - voice_assistant.start:
      #    wake_word: !lambda return wake_word;

i2s_audio:
  id: i2s_in
  i2s_lrclk_pin: GPIO25 # WS - blue
  i2s_bclk_pin: GPIO32 # SCK - yellow

microphone:
  - platform: i2s_audio
    id: va_mic
    i2s_audio_id: i2s_in
    i2s_din_pin: GPIO33 # SD - green
    adc_type: external
    #channel: left
    pdm: false
    #bits_per_sample: 32bit
    #on_data:
    #  - logger.log:
    #      format: "Received %d bytes"
    #      args: ["x.size()"]

voice_assistant:
  id: va
  microphone: va_mic
  auto_gain: 31dBFS
  noise_suppression_level: 2
  volume_multiplier: 2.0
  #vad_threshold: 3
  on_client_connected:
    then:
      - logger.log: "on_client_connected"
  on_client_disconnected:
    then:
      - logger.log: "on_client_disconnected"

  on_wake_word_detected:
    then:
      - logger.log: "on_wake_word_detected"

  on_start:
    then:
      - logger.log: "on_start"
  on_end:
    then:
      - logger.log: "on_end"
      - wait_until:
          not:
            voice_assistant.is_running:
      - micro_wake_word.start:

  on_listening:
    then:
      - logger.log: "on_listening"
      - light.turn_on: main_led

  on_stt_end:
    then:
      - light.turn_off: main_led
      - logger.log:
          format: "on_stt_end text: %s"
          args: ["x.c_str()"]

  on_intent_start:
    then:
      - logger.log: "on_intent_start"
  on_intent_end:
    then:
      - logger.log: "on_intent_end"

  on_tts_start:
    then:
      - logger.log: "on_tts_start"
  on_tts_end:
    then:
      - logger.log:
          format: "on_tts_end url: %s"
          args: ["x.c_str()"]

  on_error:
    then:
      - logger.log: "on_error"
      - light.turn_off: main_led
      - micro_wake_word.start:

button:
  - !include { file: include/button/identify.yaml }
  - !include { file: include/button/restart.yaml }
  - !include { file: include/button/safe_mode.yaml }
  - !include { file: include/button/factory_reset.yaml }

  - platform: template
    name: "Start Voice ${box_num}"
    on_press:
      - logger.log: "voice_assistant.start"
      - voice_assistant.start:
    web_server:
      sorting_group_id: sg_audio
      sorting_weight: 13

switch:
  - platform: template
    name: "Enable Wake ${box_num}"
    id: enable_wake
    icon: mdi:account-voice
    optimistic: true
    #restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - logger.log: "micro_wake_word.start"
      - micro_wake_word.start:
    turn_off_action:
      - logger.log: "micro_wake_word.stop"
      - micro_wake_word.stop:
    web_server:
      sorting_group_id: sg_audio
      sorting_weight: 11

  - platform: template
    name: "Enable Continuous ${box_num}"
    id: enable_continuous
    icon: mdi:account-voice
    optimistic: true
    #restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      #- lambda: id(va).set_use_wake_word(true);
      - if:
          condition:
            not:
              - voice_assistant.is_running:
          then:
            - logger.log: "voice_assistant.start_continuous"
            - voice_assistant.start_continuous:
    turn_off_action:
      #- lambda: id(va).set_use_wake_word(false);
      - logger.log: "voice_assistant.stop"
      - voice_assistant.stop:
    web_server:
      sorting_group_id: sg_audio
      sorting_weight: 12

  - platform: template
    name: "Start Capture ${box_num}"
    id: start_capture
    icon: mdi:account-voice
    optimistic: true
    #restore_mode: RESTORE_DEFAULT_ON
    turn_on_action:
      - logger.log: "microphone.capture: va_mic"
      - microphone.capture: va_mic
      - light.turn_on: main_led
    turn_off_action:
      - logger.log: "microphone.stop_capture: va_mic"
      - microphone.stop_capture: va_mic
      - light.turn_off: main_led
    web_server:
      sorting_group_id: sg_audio
      sorting_weight: 13

text_sensor:
  - !include { file: include/text/debug.yaml }
  - !include { file: include/text/version.yaml }
  - !include { file: include/text/wifi_info.yaml }

sensor:
  - !include { file: include/sensor/debug.yaml }
  - !include { file: include/sensor/internal_temperature.yaml }
  - !include { file: include/sensor/uptime.yaml }
  - !include { file: include/sensor/wifi_signal.yaml }
