# PIR - BENCHED

substitutions:
  # https://esphome.io/components/substitutions
  friendly_name: "Test Box 48"
  box_num: "48"
  box_name: "esptest"
  type: "esp32"
  board: "nodemcu-32s"
  comment: "38-pin (narrow)"

packages:
  # https://esphome.io/components/packages.html
  debug: !include { file: include/debug.yaml }
  common: !include { file: include/common.yaml }
  #status_led: !include
  #  file: include/status_led.yaml
  #  vars:
  #    pin: GPIO26
  counters: !include { file: include/counters.yaml }
  voice_assistant: !include { file: include/va/voice_assistant.yaml }
  micro_wake_word: !include
    file: include/va/micro_wake_word.yaml
    vars:
      model: models/jarvis.json
  discord_logs: !include
    file: include/va/discord.yaml
    vars:
      channel_id: !secret discord_va_id
  ld2420: !include
    file: include/ld2420/ld2420.yaml
    vars:
      rx_pin: GPIO16
      tx_pin: GPIO17

${type}:
  # https://esphome.io/#supported-microcontrollers
  framework:
    sdkconfig_options:
      CONFIG_ESP32_DEFAULT_CPU_FREQ_240: "y"

web_server:
  # https://esphome.io/components/web_server
  version: 3
  sorting_groups:
    - id: sg_lights
      name: "Lights"
      sorting_weight: -30

esphome:
  # https://esphome.io/components/esphome
  on_boot:
    - priority: 600
      then:
        - logger.log: "Boot 600"
        - light.turn_on:
            id: main_led
            effect: "Full Pulse"
    - priority: -100
      then:
        - logger.log: "Boot -100"
        - wait_until:
            - api.connected:
        - if:
            condition:
              - switch.is_on: micro_wake_toggle
            then:
              - light.turn_off: main_led
            else:
              - light.turn_on:
                  id: main_led
                  brightness: 20%
                  effect: None
        - !include {
            file: include/esphome/night_light_boot.yaml,
            vars: { light: night_led, switch: night_light_switch },
          }

script:
  # https://esphome.io/components/script
  - id: !extend va_end
    then:
      #- light.turn_off: main_led
      - script.execute: turn_off_led

  - id: turn_off_led
    mode: restart
    then:
      - logger.log: "Running script: turn_off_led"
      - if:
          condition:
            - switch.is_on: micro_wake_toggle
          then:
            - logger.log: "Switch micro_wake_toggle is ON: light.turn_off"
            - light.turn_off:
                id: main_led
                transition_length: 0s
          else:
            - logger.log: "Switch micro_wake_toggle is ON: light.turn_on"
            - light.turn_on:
                id: main_led
                brightness: 20%
                effect: None

voice_assistant:
  # https://esphome.io/components/voice_assistant
  on_listening:
    then:
      # Listening - We are listening to what you are saying for processing
      - light.turn_on:
          id: main_led
          brightness: 75%
          transition_length: 0s

  on_stt_vad_end:
    then:
      # STT Start - We are done listening and starting to process stt
      - light.turn_on:
          id: main_led
          effect: "Fast Pulse"

  on_tts_start:
    then:
      # TTS Start - We now have the response text from the VA
      - homeassistant.action:
          action: notify.alexa_media
          data:
            target: media_player.bedroom
          data_template:
            message: "{{ message }}"
          variables:
            message: |-
              return x.c_str();

  on_end:
    then:
      # DONE - We are done, restart micro_wake_word when VA is done...
      - script.execute: va_end

  on_error:
    then:
      # ERROR - You fucked up Chuck!
      - lambda: |-
          char formatted_message[128];
          snprintf(formatted_message, sizeof(formatted_message), "Error[%s]: %s", 
              code.c_str(), message.c_str());
          ESP_LOGI("va", "formatted_message: %s", formatted_message);

      # TODO: verify that on_end does not trigger simultaneously with on_error
      - script.execute: va_end

switch:
  # https://esphome.io/#switch-components
  - !include {
      file: include/switch/night_light.yaml,
      vars: { light: night_led, binary: presence },
    }

  - platform: homeassistant
    id: bedroom_light
    entity_id: light.bedroom_light

  - id: !remove enable_continuous
  - id: !extend micro_wake_toggle
    turn_on_action:
      - logger.log: "micro_wake_toggle: turn_on_action"
      - if:
          condition:
            not:
              voice_assistant.is_running:
          then:
            - logger.log: "micro_wake_toggle: wait_until: switch.is_on:"
            - wait_until:
                switch.is_on: micro_wake_toggle
            - logger.log: "micro_wake_toggle: script.execute: turn_off_led"
            - script.execute: turn_off_led
    turn_off_action:
      - logger.log: "micro_wake_toggle: turn_off_action"
      - if:
          condition:
            not:
              voice_assistant.is_running:
          then:
            - logger.log: "micro_wake_toggle: light.turn_on: 20"
            - light.turn_on:
                id: main_led
                brightness: 20%

#button:
#  - platform: template
#    name: "Start Capture ${box_num}"
#    id: start_capture
#    icon: mdi:account-voice
#    optimistic: true
#    #restore_mode: RESTORE_DEFAULT_ON
#    turn_on_action:
#      - logger.log: "microphone.capture: va_mic"
#      - microphone.capture: va_mic
#      - light.turn_on: main_led
#    turn_off_action:
#      - logger.log: "microphone.stop_capture: va_mic"
#      - microphone.stop_capture: va_mic
#      #- light.turn_off: main_led
#      - script.execute: turn_off_led

binary_sensor:
  # https://esphome.io/#binary-sensor-components
  - id: !extend presence_sensor
    has_target:
      !include {
        file: include/ld2420/has_target_night_light.yaml,
        vars: { light: night_led, switch: bedroom_light },
      }

  - platform: gpio
    name: "Touch 1 - ${box_num}"
    id: touch_1
    icon: mdi:gesture-tap-box
    pin:
      number: GPIO26
      mode: INPUT_PULLUP
    on_multi_click:
      - timing:
          - ON for at most 1.9s
        then:
          - logger.log: "Single Click - Start Voice"
          - script.execute: va_start
      - timing:
          - ON for at least 2s
        then:
          - logger.log: "2+ Second Touch - Toggle Wake"
          - switch.toggle: micro_wake_toggle

light:
  # https://esphome.io/components/light/
  - platform: monochromatic
    name: "Main Light ${box_num}"
    id: main_led
    icon: mdi:lightbulb-outline
    output: blue_led
    effects: !include { file: include/light/effects/pulse.yaml }
    web_server:
      sorting_group_id: sg_lights
      sorting_weight: 10

  - platform: monochromatic
    name: "Night Light ${box_num}"
    id: night_led
    icon: mdi:lightbulb-outline
    output: white_led
    effects: !include { file: include/light/effects/pulse.yaml }
    web_server:
      sorting_group_id: sg_lights
      sorting_weight: 12

output:
  # https://esphome.io/components/output/
  - platform: ledc
    id: blue_led
    pin: GPIO33
    max_power: 80%

  - platform: ledc
    id: white_led
    pin: GPIO32
    max_power: 80%

microphone:
  # https://esphome.io/components/microphone/
  - platform: i2s_audio
    id: va_mic
    i2s_audio_id: i2s_in
    i2s_din_pin: GPIO21 # SD - green
    adc_type: external
    #channel: left
    #pdm: false
    #bits_per_sample: 32bit

i2s_audio:
  # https://esphome.io/components/microphone/i2s_audio
  id: i2s_in
  i2s_lrclk_pin: GPIO23 # WS - blue
  i2s_bclk_pin: GPIO22 # SCK - yellow
