# ld2420 - Bathroom

substitutions:
  box_num: "50"
  box_name: "esptest"
  type: "esp8266"
  board: "nodemcuv2"
  comment: "full"
  update_interval: "1min"
  force_update: "true"

<<: !include .common.yaml
<<: !include { file: include/web_server.yaml, vars: { version: 3 } }

#esphome:
#  name: "${box_name}${box_num}"
#  comment: "${type}: ${board} (${comment})"
#  on_boot:
#    priority: -100
#    then:
#      - if:
#          condition:
#            - binary_sensor.is_off: bathroom_light
#          then:
#            - light.turn_off: main_led

captive_portal:

debug:
  update_interval: 5min

logger:
  level: DEBUG
  baud_rate: 0

light:
  - !include { file: include/light/status_led.yaml, vars: { pin: D5 } }

button:
  - !include { file: include/button/restart.yaml }
  - !include { file: include/button/safe_mode.yaml }
  - !include { file: include/button/factory_reset.yaml }
  - !include { file: include/ld2420/button.yaml }

select:
  - !include { file: include/ld2420/select.yaml }

number:
  - !include { file: include/ld2420/number.yaml }

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200

ld2420:

text_sensor:
  - !include { file: include/text/debug.yaml }
  - !include { file: include/text/version.yaml }
  - !include { file: include/text/wifi_info.yaml }
  - !include { file: include/ld2420/text_sensor.yaml }

binary_sensor:
  - !include { file: include/binary/status.yaml }

  - platform: ld2420
    has_target:
      name: "Presence ${box_num}"
      id: presence
      on_press:
        then:
          - logger.log: "Presence Detected"
          - wait_until:
              condition:
                binary_sensor.is_on: bathroom_light
              timeout: 8s
          - light.turn_off: main_led
      on_release:
        then:
          - logger.log: "No Presence"
          - light.turn_on: main_led

  - platform: homeassistant
    name: "Bathroom Light"
    id: bathroom_light
    entity_id: light.bathroom_light

sensor:
  - !include { file: include/sensor/debug.yaml }
  - !include { file: include/sensor/uptime.yaml }
  - !include { file: include/sensor/wifi_signal.yaml }
  - !include { file: include/ld2420/sensor.yaml }
