# ld2420 - Bathroom

substitutions:
  # https://esphome.io/components/substitutions
  friendly_name: "Test Box 50"
  box_num: "50"
  box_name: "esptest"
  type: "esp8266"
  board: "nodemcuv2"
  comment: "full"

packages:
  # https://esphome.io/components/packages.html
  #debug: !include { file: include/debug.yaml }
  common: !include { file: include/common.yaml }
  status_led: !include
    file: include/status_led.yaml
    vars:
      pin: D5
  ld2420: !include
    file: include/ld2420/ld2420.yaml
    vars:
      rx_pin: GPIO3
      tx_pin: GPIO1

${type}:
  # https://esphome.io/#supported-microcontrollers
  framework:
    type: !remove

logger:
  # https://esphome.io/components/logger
  baud_rate: 0

esphome:
  # https://esphome.io/components/esphome
  on_boot:
    - priority: -100
      then:
        - !include {
            file: include/esphome/night_light_boot.yaml,
            vars: { light: main_led, switch: night_light_switch },
          }

switch:
  # https://esphome.io/#switch-components
  - !include {
      file: include/switch/night_light.yaml,
      vars: { light: main_led, binary: presence },
    }

  - platform: homeassistant
    id: bathroom_light
    entity_id: light.bathroom_light

binary_sensor:
  # https://esphome.io/#binary-sensor-components
  - id: !extend presence_sensor
    has_target:
      !include {
        file: include/ld2420/has_target_night_light.yaml,
        vars: { light: main_led, switch: bathroom_light },
      }

  #- platform: gpio
  #  name: "Touch 1 - ${box_num}"
  #  id: touch_1
  #  icon: mdi:gesture-tap-box
  #  pin:
  #    number: 26
  #    mode: INPUT_PULLUP
  #  on_press:
  #    then:
  #      - switch.toggle: night_light_switch

sensor:
  # https://esphome.io/#sensor-components
  - id: !remove esp32_internal_temperature # not available on esp8266
