# ld2420 - Bedroom

substitutions:
  # https://esphome.io/components/substitutions
  friendly_name: "Test Box 53"
  box_num: "53"
  box_name: "esptest"
  type: "esp32"
  board: "nodemcu-32s"
  comment: "38-pin (narrow)"

packages:
  # https://esphome.io/components/packages.html
  debug: !include { file: include/debug.yaml }
  common: !include { file: include/common.yaml }
  status_led: !include
    file: include/status_led.yaml
    vars:
      pin: GPIO33
  ld2420: !include
    file: include/ld2420/ld2420.yaml
    vars:
      rx_pin: GPIO16
      tx_pin: GPIO17

${type}:
  # https://esphome.io/#supported-microcontrollers
  framework:
    sdkconfig_options:
      CONFIG_ESP32_DEFAULT_CPU_FREQ_240: "y"

esphome:
  # https://esphome.io/components/esphome
  on_boot:
    - priority: -100
      then:
        - !include {
            file: include/esphome/night_light_boot.yaml,
            vars: { light: main_led, switch: night_light },
          }

switch:
  # https://esphome.io/#switch-components
  - !include {
      file: include/switch/night_light.yaml,
      vars: { light: main_led, binary: presence },
    }

  - platform: homeassistant
    id: bedroom_light
    entity_id: light.bedroom_light

binary_sensor:
  # https://esphome.io/#binary-sensor-components
  - id: !extend presence_sensor
    has_target:
      !include {
        file: include/ld2420/has_target_night_light.yaml,
        vars: { light: main_led, switch: bedroom_light },
      }

  - platform: gpio
    name: "Touch 1 - ${box_num}"
    id: touch_1
    icon: mdi:gesture-tap-box
    pin:
      number: 26
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: night_light
