# PIR - BENCHED

substitutions:
  # https://esphome.io/components/substitutions
  box_num: "48"
  box_name: "esptest"
  type: "esp32"
  board: "nodemcu-32s"
  comment: "38-pin (narrow)"

packages:
  # https://esphome.io/components/packages.html
  debug: !include { file: include/debug.yaml }
  common: !include { file: include/common.yaml }
  status_led: !include
    file: include/status_led.yaml
    vars:
      pin: GPIO26

web_server:
  # https://esphome.io/components/web_server
  sorting_groups:
    - id: sg_lights
      name: "Lights"
      sorting_weight: -30

light:
  # https://esphome.io/components/light/
  - platform: monochromatic
    name: "Monochromatic Light ${box_num}"
    id: chromatic_led
    icon: mdi:lightbulb-outline
    output: mono_chromo
    effects: !include { file: include/light/effects/pulse.yaml }
    web_server:
      sorting_group_id: sg_lights
      sorting_weight: 10

#switch:
#  - platform: template
#    name: "Presence Light ${box_num}"
#    id: presence_light
#    icon: mdi:alarm-light-off-outline
#    optimistic: true
#    restore_mode: RESTORE_DEFAULT_OFF
#    turn_on_action:
#      - if:
#          condition:
#            - binary_sensor.is_on: presence
#          then:
#            - light.turn_on: mono_chromo
#    turn_off_action:
#      - light.turn_off: mono_chromo

#remote_receiver:
#  pin: GPIO23
#  dump: all
#  on_raw:
#    then:
#      - logger.log: "RX on_raw"
#      - light.toggle: rgb_led

output:
  - platform: ledc
    id: mono_chromo
    pin: GPIO25
    max_power: 80%

  #- platform: ledc
  #  id: rgb_r
  #  pin: GPIO27
  #  max_power: 75%
  #- platform: ledc
  #  id: rgb_g
  #  pin: GPIO14
  #  max_power: 80%
  #- platform: ledc
  #  id: rgb_b
  #  pin: GPIO12
  #  max_power: 80%

binary_sensor:
  - platform: gpio
    name: "Touch 1 - ${box_num}"
    id: touch_1
    icon: mdi:gesture-tap-box
    pin:
      number: 16
      mode: INPUT_PULLUP
    on_press:
      then:
        - light.toggle: chromatic_led

  - platform: status
    name: "Status ${box_num}"
    id: api_status
    icon: mdi:check-network-outline
    on_press:
      then:
        - logger.log: "+++ API Connected..."
    on_release:
      then:
        - logger.log: "--- API DISCONNECTED!"

  #- platform: gpio
  #  pin: GPIO19
  #  name: "Presence ${box_num}"
  #  id: presence
  #  #icon: mdi:motion-sensor
  #  device_class: motion
  #  #filters:
  #  #  - delayed_off: 60s
  #  on_press:
  #    then:
  #      - if:
  #          condition:
  #            - switch.is_on: presence_light
  #          then:
  #            - light.turn_on: main_led
  #  on_release:
  #    then:
  #      - light.turn_off: main_led

sensor:
  - platform: adc
    name: "Photoresistor ${box_num}"
    pin: GPIO36
    attenuation: 12db
    update_interval: 1s
    disabled_by_default: true
