# mmWave - Kitchen

substitutions:
  box_num: "53"
  box_name: "esptest"
  type: "esp32"
  board: "nodemcu-32s"
  comment: "38-pin (narrow)"
  update_interval: "1min"
  force_update: "true"

<<: !include .common.yaml
<<: !include { file: include/web_server.yaml, vars: { version: 3 } }

captive_portal:

debug:
  update_interval: 5min

logger:
  level: DEBUG
  baud_rate: 0

light:
  - !include { file: include/light/status_led.yaml, vars: { pin: 33 } }

button:
  - !include { file: include/button/restart.yaml }
  - !include { file: include/button/safe_mode.yaml }
  - !include { file: include/ld2420/button.yaml }

select:
  - !include { file: include/ld2420/select.yaml }

number:
  - !include { file: include/ld2420/number.yaml }

uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200

ld2420:

text_sensor:
  - !include { file: include/text/debug.yaml }
  - !include { file: include/text/version.yaml }
  - !include { file: include/text/wifi_info.yaml }
  - !include { file: include/ld2420/text_sensor.yaml }

binary_sensor:
  - !include { file: include/binary/status.yaml }

  - platform: ld2420
    has_target:
      name: "Presence ${box_num}"
      id: presence
      on_press:
        then:
          - logger.log: "+++ PRESENCE DETECTED"
          - light.turn_on: main_led
      on_release:
        then:
          - logger.log: "--- NO PRESENCE"
          - light.turn_off: main_led

sensor:
  - !include { file: include/sensor/debug.yaml }
  - !include { file: include/sensor/internal_temperature.yaml }
  - !include { file: include/sensor/uptime.yaml }
  - !include { file: include/sensor/wifi_signal.yaml }
  - !include { file: include/ld2420/sensor.yaml }
