if:
  condition:
    - binary_sensor.is_on: presence
    - light.is_on: ${light}
  then:
    - logger.log: "Turning Off: main_led"
    - light.turn_off: ${light}
  else:
    - if:
        condition:
          - switch.is_on: ${switch}
        then:
          - logger.log: "Turning On: main_led"
          - light.turn_on: ${light}
