substitutions:
  box_num: "51"
  box_name: "esptest"
  run_time: "4s"
  sleep_time: "2min"
  update_interval: "${sleep_time}"

esphome:
  name: "${box_name}${box_num}"
  friendly_name: "${box_num} - Test Deep Sleep"
  comment: "esp32 38-pin"
  on_boot:
    priority: -100.0
    then:
      - script.execute: deep_sleep_evaluation

esp32:
  board: esp32dev

logger:
  level: WARN
  baud_rate: 0

api:
  encryption:
    key: !secret enc_key

ota:
  password: !secret ota_pass
  reboot_timeout: 10min
  id: ota_one

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  domain: !secret local_domain
  fast_connect: true
  power_save_mode: high
  output_power: 8.5dB
  use_address: 192.168.1.2${box_num}
  manual_ip:
    static_ip: 192.168.1.2${box_num}
    gateway: 192.168.1.1
    subnet: 255.255.255.0

button:
  - platform: restart
    name: "Reboot Device ${box_num}"
    id: reboot_device
    
  - platform: safe_mode
    name: "Reboot Safe Mode ${box_num}"

deep_sleep:
  sleep_duration: "${sleep_time}"
  id: deep_sleep_enabled

script:
  - id: deep_sleep_evaluation
    mode: queued
    then:
      - delay: "${run_time}"
      - if:
          condition:
            binary_sensor.is_on: disable_deep_sleep
          then:
            - logger.log: 'Deep Sleep Disabled'
          else:
            - deep_sleep.enter: deep_sleep_enabled
      - script.execute: deep_sleep_evaluation

binary_sensor:
  - platform: homeassistant
    id: disable_deep_sleep
    entity_id: input_boolean.disable_deep_sleep

sensor:
  - platform: wifi_signal
    name: "WiFi Signal ${box_num}"
    update_interval: "${update_interval}"
    force_update: true

  - platform: dht
    model: DHT22
    pin:
      number: GPIO33
      mode: INPUT_PULLUP
    update_interval: "${update_interval}"
    temperature:
      name: "TestTemp${box_num}-22"
      filters:
        - filter_out: 80
        - filter_out: -40
    humidity:
      name: "TestHumi${box_num}-22"
      accuracy_decimals: 1
      filters:
        - filter_out: 0
