# micro_wake_word: !include { file: include/va/micro_wake_word.yaml }
# micro_wake_word: !include
#   file: include/va/micro_wake_word.yaml
#   vars:
#     model: hey_jarvis
#     sorting_group_id: sg_va
# https://esphome.io/components/micro_wake_word

substitutions:
  model: "hey_jarvis"
  sorting_group_id: "sg_va"

esphome:
  on_boot:
    - priority: -113
      then:
        - logger.log: "Boot -113"
        - if:
            condition:
              - switch.is_on: micro_wake_toggle
            then:
              - logger.log: "Enabling Micro Wake Word..."
              - script.execute: micro_wake_enable
              #- micro_wake_word.start:

micro_wake_word:
  vad:
  models:
    - model: ${model}
  on_wake_word_detected:
    then:
      - logger.log: "on_wake_word_detected"
      - voice_assistant.start:

script:
  - id: micro_wake_enable
    then:
      - logger.log: "Running script: micro_wake_enable"
      - if:
          condition:
            not:
              voice_assistant.is_running:
          then:
            - logger.log: "micro_wake_enable: micro_wake_word.start"
            - micro_wake_word.start:

  - id: va_start
    mode: restart
    then:
      - logger.log: "Running script: va_start"
      - if:
          condition:
            - voice_assistant.is_running:
          then:
            - logger.log: "va_start: voice_assistant.stop"
            - voice_assistant.stop:
          else:
            - logger.log: "va_start: micro_wake_word.stop"
            - micro_wake_word.stop:
            - wait_until:
                condition:
                  not:
                    microphone.is_capturing:
                #timeout: 1000ms
            - logger.log: "va_start: voice_assistant.start"
            - voice_assistant.start:

  - id: va_end
    mode: restart
    then:
      - logger.log: "Running script: va_end"
      - if:
          condition:
            switch.is_on: micro_wake_toggle
          then:
            - wait_until:
                not:
                  voice_assistant.is_running:
            - logger.log: "va_end: micro_wake_word.start"
            - micro_wake_word.start:

switch:
  - platform: template
    name: "Enable Wake ${box_num}"
    id: micro_wake_toggle
    icon: mdi:account-voice
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    turn_on_action:
      - logger.log: "Enable Micro Wake Word"
      - script.execute: micro_wake_enable
    turn_off_action:
      - logger.log: "Disable Micro Wake Word"
      - micro_wake_word.stop:
    web_server:
      sorting_group_id: sg_va
      sorting_weight: -30
