# ld2420: !include
#   file: include/ld2420/ld2420.yaml
#   vars:
#     rx_pin: GPIO16
#     tx_pin: GPIO17
# https://esphome.io/components/sensor/ld2420

uart:
  rx_pin: ${rx_pin}
  tx_pin: ${tx_pin}
  baud_rate: 115200

ld2420:

number:
  - !include { file: number.yaml }

select:
  - !include { file: select.yaml }

button:
  - !include { file: button.yaml }

text_sensor:
  - !include { file: text_sensor.yaml }

sensor:
  - !include { file: sensor.yaml }
