# https://esphome.io/components/sensor/ld2420

uart:
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  baud_rate: 115200

ld2420:

number:
  - !include { file: number.yaml }

select:
  - !include { file: select.yaml }

button:
  - !include { file: button.yaml }

text_sensor:
  - !include { file: text_sensor.yaml }

#binary_sensor:
#  - !include { file: binary.yaml }

sensor:
  - !include { file: sensor.yaml }
