# debug: !include { file: include/debug.yaml }
# https://esphome.io/components/debug

debug:
  update_interval: 5min

text_sensor:
  - !include { file: text/debug.yaml }

sensor:
  - !include { file: sensor/debug.yaml }
