# https://esphome.io/components/debug
# debug: github://smashedr/esphome-configs/include/debug.yaml@master
# debug: !include
#   file: include/debug.yaml
#   vars:
#     box_num: 01

substitutions:
  box_num: "01"

debug:
  update_interval: 5min

text_sensor:
  - !include { file: text/debug.yaml }

sensor:
  - !include { file: sensor/debug.yaml }
