# Refrigerator/Front Door - Kitchen

substitutions:
  box_num: "49"
  box_name: "esptest"
  type: "esp32"
  board: "nodemcu-32s"
  comment: "38-pin (narrow)"
  update_interval: "1min"
  force_update: "true"

<<: !include { file: .common.yaml }
<<: !include { file: include/web/web_server.yaml, vars: { version: 3 } }

captive_portal:

esphome:
  name: "${box_name}${box_num}"
  comment: "${type}: ${board} (${comment})"
  on_boot:
    - priority: 600
      then:
        - rtttl.play: "SMWTheme:d=4,o=6,b=100:16e,16e,32p,8e,16c,8e,8g,8p,8g5,8p"
    #- priority: -100
    #  then:
    #    - if:
    #        condition:
    #          - switch.is_on: kitchen_light
    #          - light.is_on: main_led
    #        then:
    #          - logger.log: "Turning Off: main_led"
    #          - light.turn_off: main_led
    #        else:
    #          - if:
    #              condition:
    #                - switch.is_on: night_light
    #              then:
    #                - logger.log: "Turning On: main_led"
    #                - light.turn_on: main_led
#- priority: 200
#  then:
#    - switch.turn_off: buzzer
#    - delay: 30s
#    - if:
#        condition:
#          - binary_sensor.is_off: alarm_arm
#        then:
#          - light.turn_off: red_led
#    - if:
#        condition:
#          - binary_sensor.is_on: alarm_arm
#        then:
#          - light.turn_on: red_led

api:
  encryption:
    key: !secret enc_key
  services:
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda "return song_str;"

debug:
  update_interval: 5min

light:
  - !include { file: include/light/status_led.yaml, vars: { pin: 32 } }

  - platform: binary
    name: "Red LED ${box_num}"
    id: red_led
    output: red_out

#switch:
#  - platform: template
#    name: "Night Light ${box_num}"
#    id: night_light
#    icon: mdi:lightbulb-night
#    optimistic: true
#    turn_on_action:
#      #- logger.log: "Light Enabled"
#      - if:
#          condition:
#            switch.is_off: kitchen_light
#          then:
#            - light.turn_on: main_led
#    turn_off_action:
#      #- logger.log: "Light Disabled"
#      - light.turn_off: main_led
#
#  - platform: homeassistant
#    name: "Kitchen Light"
#    id: kitchen_light
#    entity_id: light.kitchen
#    on_turn_on:
#      then:
#        - logger.log: "Kitchen Light On"
#        - light.turn_off: main_led
#    on_turn_off:
#      then:
#        - if:
#            condition:
#              - switch.is_on: night_light
#            then:
#              - logger.log: "Kitchen Light Off"
#              - light.turn_on: main_led

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: false
  frequency: 400kHz

output:
  - platform: gpio
    id: red_out
    pin: GPIO33

  - platform: ledc
    pin: GPIO27
    id: rtttl_out

rtttl:
  output: rtttl_out
#  on_finished_playback:
#    - logger.log: "Playback Finished."

#one_wire:
#  - platform: gpio
#    pin: GPIO33

font:
  - file: "fonts/arial.ttf"
    id: font1
    size: 14
  - file: "fonts/arial.ttf"
    id: font2
    size: 16

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    #reset_pin: D0
    #update_interval: 5s
    lambda: |-
      if (!global_api_server->is_connected() ) {
        it.printf(0, 0, id(font1), "Connecting to HA...");
        it.printf(0, 23, id(font1), "IP:");
        it.printf(128, 23, id(font1), TextAlign::RIGHT, "%s", WiFi.localIP().toString().c_str());

      } else {
        it.printf(0, 0, id(font1), "IP:");
        it.printf(128, 0, id(font1), TextAlign::RIGHT, "%s", WiFi.localIP().toString().c_str());

        it.printf(0, 23, id(font2), "Doors:");
        if (id(door_sensor_1).state) {
          it.printf(128, 23, id(font2), TextAlign::RIGHT, "FREEZER");
        } else if (id(door_sensor_2).state) {
          it.printf(128, 23, id(font2), TextAlign::RIGHT, "FRIDGE");
        } else if (id(door_sensor_3).state) {
          it.printf(128, 23, id(font2), TextAlign::RIGHT, "FRONT");
        } else {
          it.printf(128, 23, id(font2), TextAlign::RIGHT, "Closed");
        }

        it.printf(0, 46, id(font2), "Alarm:");
        // it.printf(128, 46, id(font2), TextAlign::RIGHT, "%s", id(alarm_active));
        if (id(alarm_active).state) {
          it.printf(128, 46, id(font2), TextAlign::RIGHT, "%s", "ACTIVE");
        } else if (id(alarm_arm).state) {
          it.printf(128, 46, id(font2), TextAlign::RIGHT, "%s", "ARMED");
        } else {
          it.printf(128, 46, id(font2), TextAlign::RIGHT, "%s", "Disarmed");
        }

        // it.printf(0, 0, id(font1), "IP:");
        // it.printf(128, 0, id(font1), TextAlign::RIGHT, "%s", id(wifi_ip).state.c_str());

        // it.printf(0, 23, id(font2), "Fridge:");
        // it.printf(128, 23, id(font2), TextAlign::RIGHT, "%.1f°F", id(temp1).state * 1.8 + 32);

        // it.printf(0, 46, id(font2), "Freezer:");
        // it.printf(128, 46, id(font2), TextAlign::RIGHT, "%.1f°F", id(temp2).state * 1.8 + 32);
      }

      // it.printf(0, 23, id(font1), "IP:");
      // it.printf(128, 23, id(font1), TextAlign::RIGHT, "%s", WiFi.localIP().toString().c_str());

text_sensor:
  - !include { file: include/text/debug.yaml }
  - !include { file: include/text/version.yaml }
  - !include { file: include/text/wifi_info.yaml }

  #- platform: homeassistant
  #  name: "WiFi IP Address"
  #  id: wifi_ip
  #  entity_id: sensor.wifi_ip_49

binary_sensor:
  - !include { file: include/binary/status.yaml }

  - platform: gpio
    name: "Door Freezer"
    id: door_sensor_1
    device_class: door
    pin:
      number: 19
      mode: INPUT_PULLUP
    on_press:
      then:
        - logger.log: "Freezer --- OPEN"
        # - rtttl.play: "one:d=4,o=4,b=240:6e6"
        - light.turn_on: main_led
    on_release:
      then:
        - logger.log: "Freezer --- CLOSED"
        - rtttl.play: "one:d=4,o=4,b=240:6e6"
        - if:
            condition:
              binary_sensor.is_off: door_sensor_2
            then:
              - light.turn_off: main_led

  - platform: gpio
    name: "Door Refrigerator"
    id: door_sensor_2
    device_class: door
    pin:
      number: 18
      mode: INPUT_PULLUP
    on_press:
      then:
        - logger.log: "Refrigerator --- OPEN"
        # - rtttl.play: "one:d=4,o=4,b=240:6e6"
        - light.turn_on: main_led
    on_release:
      then:
        - logger.log: "Refrigerator --- CLOSED"
        - rtttl.play: "one:d=4,o=4,b=240:6e6"
        - if:
            condition:
              binary_sensor.is_off: door_sensor_1
            then:
              - light.turn_off: main_led

  - platform: gpio
    name: "Door Front"
    id: door_sensor_3
    device_class: door
    pin:
      number: 5
      mode: INPUT_PULLUP
    on_press:
      then:
        - logger.log: "DOOR --- OPEN"
        - if:
            condition:
              - binary_sensor.is_off: alarm_active
            then:
              - rtttl.play: "HiLoLong:d=4,o=6,b=200:e,8d,2e"
            #else:
            #  - while:
            #      condition:
            #        binary_sensor.is_on: alarm_active
            #      then:
            #        - rtttl.play: "siren:d=8,o=5,b=100:d,e,d,e,d,e,d,e"
    on_release:
      then:
        - logger.log: "DOOR --- CLOSED"
        - if:
            condition:
              - binary_sensor.is_off: alarm_active
            then:
              - rtttl.play: "EBeep:d=1,o=5,b=100:8e6"

  - platform: homeassistant
    id: alarm_arm
    entity_id: input_boolean.alarm_arm
    on_state:
      then:
        - if:
            condition:
              - binary_sensor.is_off: alarm_arm
            then:
              - logger.log: "ALARM --- DISARM"
              - light.turn_off: red_led
        - if:
            condition:
              - binary_sensor.is_on: alarm_arm
            then:
              - logger.log: "ALARM --- ARM"
              - light.turn_on: red_led

  - platform: homeassistant
    id: alarm_active
    entity_id: input_boolean.alarm_active
    on_state:
      then:
        - if:
            condition:
              - binary_sensor.is_off: alarm_active
            then:
              - logger.log: "ALARM --- OFF"
        - if:
            condition:
              - binary_sensor.is_on: alarm_active
            then:
              - logger.log: "ALARM --- ACTIVATE"
              - while:
                  condition:
                    binary_sensor.is_on: alarm_active
                  then:
                    - rtttl.play: "siren:d=8,o=5,b=100:d,e,d,e,d,e,d,e"

  #- platform: gpio
  #  pin:
  #    number: 19
  #    mode: INPUT_PULLUP
  #  name: "Physical Button ${box_num}"
  #  icon: mdi:radiobox-marked
  #  filters:
  #    - invert:
  #  on_click:
  #    - min_length: 1ms
  #      max_length: 1000ms
  #      then:
  #        - logger.log: ">1 Second Single Click"
  #        - light.toggle: main_led
  #    - min_length: 1001ms
  #      max_length: 4999ms
  #      then:
  #        - logger.log: "1-5 Second Long Press"
  #    - min_length: 5000ms
  #      max_length: 10000ms
  #      then:
  #        - logger.log: "5< Second Long Press"

sensor:
  - !include { file: include/sensor/debug.yaml }
  - !include { file: include/sensor/internal_temperature.yaml }
  - !include { file: include/sensor/uptime.yaml }
  - !include { file: include/sensor/wifi_signal.yaml }
